name: speedometer
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  sensors_plus: ^1.3.3

  flutter_bloc: 9.0.0
  bloc: 9.0.0
  equatable: ^2.0.7
  freezed_annotation: ^2.4.4


  cupertino_icons: ^1.0.2

  geolocator: ^13.0.2
  logging: ^1.3.0
  sentry_flutter: ^8.13.0

dev_dependencies:
  freezed: ^2.5.8
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
